"""create base tables


Revision ID: 0001_create_base_tables
Revises:
Create Date: 2025-12-04 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_create_base_tables'
down_revision = None
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('ticker', sa.String(length=32), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=True),
                    sa.Column('exchange', sa.String(length=32), nullable=True),
                    sa.Column('sector', sa.String(length=128), nullable=True),
                    sa.Column('industry', sa.String(length=128), nullable=True),
                    sa.Column('currency', sa.String(length=8), nullable=True),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.UniqueConstraint('ticker', name='uq_stocks_ticker')
    )


    op.create_table('stock_prices',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('stock_id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('open', sa.Numeric(), nullable=True),
                    sa.Column('high', sa.Numeric(), nullable=True),
                    sa.Column('low', sa.Numeric(), nullable=True),
                    sa.Column('close', sa.Numeric(), nullable=True),
                    sa.Column('volume', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
                    sa.UniqueConstraint('stock_id', 'date', name='uq_stock_date')
    )


    op.create_table('dividends',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('stock_id', sa.Integer(), nullable=False),
                    sa.Column('ex_date', sa.Date(), nullable=False),
                    sa.Column('pay_date', sa.Date(), nullable=True),
                    sa.Column('record_date', sa.Date(), nullable=True),
                    sa.Column('declared_date', sa.Date(), nullable=True),
                    sa.Column('amount', sa.Numeric(), nullable=False),
                    sa.Column('frequency', sa.String(length=32), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
                    sa.UniqueConstraint('stock_id', 'ex_date', name='uq_dividend_stock_exdate')
    )


    op.create_table('holdings',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('stock_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Numeric(), nullable=False, server_default='0'),
                    sa.Column('cost_basis', sa.Numeric(), nullable=False, server_default='0'),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
                    sa.UniqueConstraint('stock_id', name='uq_holdings_stock')
                    )


    op.create_table('transactions',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('stock_id', sa.Integer(), nullable=True),
                    sa.Column('type', sa.String(length=32), nullable=False),
                    sa.Column('quantity', sa.Numeric(), nullable=True),
                    sa.Column('price', sa.Numeric(), nullable=True),
                    sa.Column('total', sa.Numeric(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='SET NULL')
    )


    op.create_table('portfolio_metrics',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('total_value', sa.Numeric(), nullable=True),
                    sa.Column('total_dividends', sa.Numeric(), nullable=True),
                    sa.Column('forward_dividend_income', sa.Numeric(), nullable=True),
                    sa.Column('yield_on_cost', sa.Numeric(), nullable=True),
                    sa.UniqueConstraint('date', name='uq_portfolio_metrics_date')
    )


    op.create_table('alerts',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('stock_id', sa.Integer(), nullable=True),
                    sa.Column('type', sa.String(length=64), nullable=True),
                    sa.Column('message', sa.String(length=1024), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('resolved', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE')
    )


    op.create_table('ai_analysis',
                    sa.Column('id', sa.Integer(), primary_key=True),
                    sa.Column('stock_id', sa.Integer(), nullable=True),
                    sa.Column('analysis_type', sa.String(length=128), nullable=True),
                    sa.Column('content', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE')
)
# ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis')
    op.drop_table('alerts')
    op.drop_table('portfolio_metrics')
    op.drop_table('transactions')
    op.drop_table('holdings')
    op.drop_table('dividends')
    op.drop_table('stock_prices')
    op.drop_table('stocks')
    # ### end Alembic commands ###