"""Add date column to dividends

Revision ID: aa6923ce1d65
Revises: 0001_create_base_tables
Create Date: 2025-12-05 21:36:42.537655

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'aa6923ce1d65'
down_revision = '0001_create_base_tables'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividends', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dividends', 'date')
    # ### end Alembic commands ###
