"""Allow nulls in dividend table

Revision ID: cb35a59b646f
Revises: aa6923ce1d65
Create Date: 2025-12-05 22:04:52.160183

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cb35a59b646f'
down_revision = 'aa6923ce1d65'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividends', 'ex_date', nullable=True)
    op.alter_column('dividends', 'pay_date', nullable=True)
    op.alter_column('dividends', 'record_date', nullable=True)
    op.alter_column('dividends', 'declared_date', nullable=True)
    op.alter_column('dividends', 'frequency', nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dividends', 'ex_date', nullable=False)
    op.alter_column('dividends', 'pay_date', nullable=False)
    op.alter_column('dividends', 'record_date', nullable=False)
    op.alter_column('dividends', 'declared_date', nullable=False)
    op.alter_column('dividends', 'frequency', nullable=False)
    # ### end Alembic commands ###
